name: Mibuz
markdown: redcarpet
assets_css: /assets/stylesheets/style.css
assets_js: /assets/stylesheets/main.js
pygments: true
permalink: pretty
exclude:
- '.gitignore'
- '.sass-cache'
- 'CNAME'
- 'config.rb'
- 'Gemfile'
- 'Gemfile.lock'
- 'Guardfile'
- 'Procfile'
- 'README.md'
- 'sass'
